namespace TypedSignalR.Client.DevTools.Templates;

public sealed class CoreTemplate : ITextTemplate
{
    public string TransformText()
    {
        return @"// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY TypedSignalR.Client.DevTools
// </auto-generated>
using System;
using System.Buffers;
using System.Diagnostics;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace TypedSignalR.Client.DevTools;

public static partial class EndpointRouteBuilderExtensions
{
    /// <summary>
    /// /signalr-dev/spec.json
    /// </summary>
    public static void UseSignalRHubSpecification(this IEndpointRouteBuilder endpointRouteBuilder)
    {
        // Actually, it does not use middleware.
        endpointRouteBuilder.MapGet(""/signalr-dev/spec.json"", (HttpContext context) =>
        {
            context.Response.StatusCode = StatusCodes.Status200OK;
            context.Response.ContentType = ""application/json"";

            context.Response.BodyWriter.Write(GetSpecJsonBytes());
            context.Response.BodyWriter.Complete();
        });
    }

    private static partial ReadOnlySpan<byte> GetSpecJsonBytes();
}
";
    }
}
