// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY TypedSignalR.Client.DevelopmentUI
// </auto-generated>
#nullable enable
using System.Collections.Generic;

namespace TypedSignalR.Client.DevTools;

public static class EmbeddedResourcePathProvider
{
    private static readonly string[] _paths = new[]
    {
        "signalr-dev/404.html",
        "signalr-dev/index.html",
        "signalr-dev/spec-test.json",
        "signalr-dev/_next/static/chunks/97-3247e2d57fb64c2a.js",
        "signalr-dev/_next/static/chunks/framework-7751730b10fa0f74.js",
        "signalr-dev/_next/static/chunks/main-19f18dac8026c78d.js",
        "signalr-dev/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js",
        "signalr-dev/_next/static/chunks/webpack-8985bb90fc6ade1b.js",
        "signalr-dev/_next/static/chunks/pages/index-fd63c8be9d9399e5.js",
        "signalr-dev/_next/static/chunks/pages/_app-35c64dd111690593.js",
        "signalr-dev/_next/static/chunks/pages/_error-e4f561a102d9bb14.js",
        "signalr-dev/_next/static/css/276ae7c0387fc2e1.css",
        "signalr-dev/_next/static/F8GCcZC0KAUzdlfCGpHhM/_buildManifest.js",
        "signalr-dev/_next/static/F8GCcZC0KAUzdlfCGpHhM/_ssgManifest.js",
    };

    public static IReadOnlyList<string> GetPaths() => _paths;
}
