// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY TypedSignalR.Client.DevelopmentUI
// </auto-generated>
#nullable enable
using System.Collections.Generic;

namespace TypedSignalR.Client.DevTools;

internal static class EmbeddedResourcePathProvider
{
    private static readonly string[] _paths = new[]
    {
        "signalr-dev/404.html",
        "signalr-dev/index.html",
        "signalr-dev/spec-test.json",
        "signalr-dev/_next/static/chunks/830-9d48ffa709498335.js",
        "signalr-dev/_next/static/chunks/framework-2c79e2a64abdb08b.js",
        "signalr-dev/_next/static/chunks/main-558fc47eb84446ba.js",
        "signalr-dev/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js",
        "signalr-dev/_next/static/chunks/webpack-e65c1d101fc3e111.js",
        "signalr-dev/_next/static/chunks/pages/index-da9b02e27c214c1f.js",
        "signalr-dev/_next/static/chunks/pages/_app-3fbddd7878bee85f.js",
        "signalr-dev/_next/static/chunks/pages/_error-8353112a01355ec2.js",
        "signalr-dev/_next/static/css/eecc0ebe6e775f93.css",
        "signalr-dev/_next/static/EXbk27KQSM-qv6yzRb185/_buildManifest.js",
        "signalr-dev/_next/static/EXbk27KQSM-qv6yzRb185/_ssgManifest.js",
    };

    public static IReadOnlyList<string> GetPaths() => _paths;
}
